kind = "web"
previewPath = "/"
title = "Procjus Premium"
version = "1.0.0"
id = "artifacts/jusbrasil"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24265

[services.development]
run = "pnpm --filter @workspace/jusbrasil run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jusbrasil", "run", "build" ]
publicDir = "artifacts/jusbrasil/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24265"
BASE_PATH = "/"
