// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/form-header-variants/OptionB.tsx": () => import("../components/mockups/form-header-variants/OptionB.tsx"),
  "./components/mockups/form-header-variants/OptionC.tsx": () => import("../components/mockups/form-header-variants/OptionC.tsx"),
  "./components/mockups/hero-form-variants/AccessibilityFirst.tsx": () => import("../components/mockups/hero-form-variants/AccessibilityFirst.tsx"),
  "./components/mockups/hero-form-variants/AffordanceFirst.tsx": () => import("../components/mockups/hero-form-variants/AffordanceFirst.tsx"),
  "./components/mockups/hero-form-variants/HierarchyFirst.tsx": () => import("../components/mockups/hero-form-variants/HierarchyFirst.tsx")
};
