import { db, blogPostsTable } from "@workspace/db";

export async function seedBlog() {
  const count = await db.$count(blogPostsTable);
  if (count > 0) return;

  console.log("[seed] Blog vazio, inserindo artigos...");
  await db.insert(blogPostsTable).values([
    { uuid: 'a1b2c3d4-1111-4000-a000-000000000001', slug: 'voo-cancelado-direitos-indenizacao', title: 'Voo Cancelado ou Atrasado? Conheça Seus Direitos e Como Pedir Indenização', summary: 'Saiba seus direitos segundo a ANAC e como conseguir indenização 100% online.', content: '<h2>Voo cancelado: o que a lei diz</h2><p>A Resolução 400 da ANAC estabelece regras para cancelamento, atraso ou overbooking.</p><h2>Seus direitos</h2><p><strong>1h:</strong> comunicação. <strong>2h:</strong> alimentação. <strong>4h:</strong> hospedagem.</p><h2>Indenização</h2><p>R$ 3.000 a R$ 15.000.</p><h2>Prazo</h2><p>Nacionais: 5 anos. Internacionais: 2 anos.</p><h2>Pequenas Causas Processos</h2><p>Advogado de verdade, 100% online, só paga se ganhar.</p>', category: 'Direito do Passageiro', publishedAt: new Date('2026-04-01') },
    { uuid: 'a1b2c3d4-2222-4000-a000-000000000002', slug: 'negativacao-indevida-nome-sujo-indenizacao', title: 'Negativação Indevida: Como Tirar Seu Nome do SPC/Serasa e Receber Indenização', summary: 'Entenda seus direitos e como buscar indenização de até R$ 10.000.', content: '<h2>O que é</h2><p>Nome no SPC/Serasa injustamente.</p><h2>CDC</h2><p>Empresa deve notificar antes. 5 dias para retirar após pagamento.</p><h2>Valores</h2><p>R$ 3.000 a R$ 10.000.</p><h2>Pequenas Causas Processos</h2><p>Advogado de verdade, online, só paga se ganhar.</p>', category: 'Direito do Consumidor', publishedAt: new Date('2026-04-02') },
    { uuid: 'a1b2c3d4-3333-4000-a000-000000000003', slug: 'restituicao-inss-dois-empregos', title: 'Restituição de INSS: Quem Trabalha em Dois Empregos Pode Ter Até R$ 60 Mil', summary: 'Pode estar pagando INSS acima do teto. Saiba como pedir restituição.', content: '<h2>Por que perde dinheiro</h2><p>Cada empregador desconta separado. Soma acima do teto = pagando demais.</p><h2>Quem tem direito</h2><p>2+ empregos nos últimos 5 anos.</p><h2>Valores</h2><p>R$ 20.000 a R$ 60.000.</p><h2>Pequenas Causas Processos</h2><p>Advogado de verdade, online, só paga se receber.</p>', category: 'INSS e Previdência', publishedAt: new Date('2026-04-03') },
    { uuid: 'a1b2c3d4-4444-4000-a000-000000000004', slug: 'como-entrar-processo-juizado-especial-2026', title: 'Como Entrar com Processo no Juizado Especial: Guia Completo 2026', summary: 'Guia completo: quem pode, limite de valor, documentos e prazos.', content: '<h2>O que é</h2><p>Lei 9.099/95, causas de menor valor.</p><h2>Quem pode</h2><p>Pessoas físicas, MEs, EPPs. Limite: 40 SM.</p><h2>Tipos</h2><p>Cobranças indevidas, defeitos, negativação, voos.</p><h2>Prazo</h2><p>3 a 6 meses.</p><h2>Pequenas Causas Processos</h2><p>Advogado de verdade, 100% online, menor percentual.</p>', category: 'Juizado Especial', publishedAt: new Date('2026-04-04') },
    { uuid: 'a1b2c3d4-5555-4000-a000-000000000005', slug: 'cobranca-indevida-conta-luz-agua-telefone', title: 'Cobrança Indevida: Conta de Luz, Água ou Telefone', summary: 'Seus direitos ao reembolso em dobro e indenização.', content: '<h2>A lei</h2><p>CDC artigo 42: devolução em dobro.</p><h2>Exemplos</h2><p>Energia acima do consumo, telefone não contratado, religação indevida.</p><h2>Pequenas Causas Processos</h2><p>Qualquer causa de consumidor. Advogado de verdade, online, só paga se ganhar.</p>', category: 'Direito do Consumidor', publishedAt: new Date('2026-04-05') },
  ]);
  console.log("[seed] 5 artigos inseridos!");
}
